### ISSUE TITLE
Matching parent size

### ISSUE THREAD

**Issue by julasamer** [getwagit/Baya#64]
I expected `layout.layoutMatchingParentWidth().layoutMatchingParentHeight()` to have the same effect as `layout.layoutMatchingParent()`.

Instead, it looks like the latter call overrides the former: the layout wraps the content width and matches the parent's height.

**Comment by marcorei** [comment]
Good catch.

Currently [`layoutMatchingParentHeight()`](https://github.com/getwagit/Baya/blob/master/Baya/layouts/BayaMatchParentLayout.swift#L53) just sets the `BayaLayoutOptions.Mode` for `width` to `.wrapContent` instead of using the one of the child. Similar with `layoutMatchingParentWidth()`.

I'll change that later and see if this breaks anything.
